=== PurdueElectricRacing/firmware/common/can_library/schema/external_node_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "required": ["node_name", "bus_name"],
    "additionalProperties": false,
    "properties": {
        "node_name": { "type": "string" },
        "bus_name": { "type": "string" },
        "tx": {
            "type": "array",
            "items": { "$ref": "file:///message_schema.json#/$defs/tx_message" }
        },
        "rx": {
            "type": "array",
            "items": { "$ref": "file:///message_schema.json#/$defs/rx_message" }
        }
    }
}

=== PurdueElectricRacing/firmware/common/can_library/configs/external_nodes/BITSTREAM.json
{
    "node_name": "BITSTREAM",
    "bus_name": "VCAN",
    "tx": [
        {
            "msg_name": "bitstream_data",
            "msg_desc": "Bitstream download command",
            "signals": [
                {
                    "sig_name": "d0",
                    "sig_desc": "Bitstream data word 0",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "d1",
                    "sig_desc": "Bitstream data word 1",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "d2",
                    "sig_desc": "Bitstream data word 2",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "d3",
                    "sig_desc": "Bitstream data word 3",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "d4",
                    "sig_desc": "Bitstream data word 4",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "d5",
                    "sig_desc": "Bitstream data word 5",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "d6",
                    "sig_desc": "Bitstream data word 6",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "d7",
                    "sig_desc": "Bitstream data word 7",
                    "type": "uint8_t",
                    "length": 8
                }
            ],
            "msg_period": 0,
            "msg_priority": 3
        },
        {
            "msg_name": "bitstream_request",
            "msg_desc": "Bitstream state command",
            "signals": [
                {
                    "sig_name": "download_request",
                    "sig_desc": "Request to download new bitstream",
                    "type": "uint8_t",
                    "length": 1
                },
                {
                    "sig_name": "download_size",
                    "sig_desc": "size for expected bitstream download (bytes)",
                    "type": "uint32_t",
                    "length": 32
                }
            ],
            "msg_period": 0,
            "msg_priority": 3
        },
        {
            "msg_name": "main_module_bl_cmd",
            "msg_desc": "Bootloader command for main module",
            "signals": [
                {
                    "sig_name": "cmd",
                    "sig_desc": "Bootloader Command type",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "data",
                    "sig_desc": "Bootloader data",
                    "type": "uint32_t",
                    "length": 32
                }
            ],
            "msg_period": 0,
            "msg_priority": 3
        },
        {
            "msg_name": "dashboard_bl_cmd",
            "msg_desc": "Bootloader command for dashboard",
            "signals": [
                {
                    "sig_name": "cmd",
                    "sig_desc": "Bootloader Command type",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "data",
                    "sig_desc": "Bootloader data",
                    "type": "uint32_t",
                    "length": 32
                }
            ],
            "msg_period": 0,
            "msg_priority": 3
        },
        {
            "msg_name": "torquevector_bl_cmd",
            "msg_desc": "Bootloader command for torque vector",
            "signals": [
                {
                    "sig_name": "cmd",
                    "sig_desc": "Bootloader Command type",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "data",
                    "sig_desc": "Bootloader data",
                    "type": "uint32_t",
                    "length": 32
                }
            ],
            "msg_period": 0,
            "msg_priority": 3
        },
        {
            "msg_name": "a_box_bl_cmd",
            "msg_desc": "Bootloader command for a-box",
            "signals": [
                {
                    "sig_name": "cmd",
                    "sig_desc": "Bootloader Command type",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "data",
                    "sig_desc": "Bootloader data",
                    "type": "uint32_t",
                    "length": 32
                }
            ],
            "msg_period": 0,
            "msg_priority": 3
        },
        {
            "msg_name": "pdu_bl_cmd",
            "msg_desc": "Bootloader command for pdu",
            "signals": [
                {
                    "sig_name": "cmd",
                    "sig_desc": "Bootloader Command type",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "data",
                    "sig_desc": "Bootloader data",
                    "type": "uint32_t",
                    "length": 32
                }
            ],
            "msg_period": 0,
            "msg_priority": 3
        },
        {
            "msg_name": "l4_testing_bl_cmd",
            "msg_desc": "Bootloader command for l4 testing",
            "signals": [
                {
                    "sig_name": "cmd",
                    "sig_desc": "Bootloader Command type",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "data",
                    "sig_desc": "Bootloader data",
                    "type": "uint32_t",
                    "length": 32
                }
            ],
            "msg_period": 0,
            "msg_priority": 3
        },
        {
            "msg_name": "f4_testing_bl_cmd",
            "msg_desc": "Bootloader command for f4 testing",
            "signals": [
                {
                    "sig_name": "cmd",
                    "sig_desc": "Bootloader Command type",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "data",
                    "sig_desc": "Bootloader data",
                    "type": "uint32_t",
                    "length": 32
                }
            ],
            "msg_period": 0,
            "msg_priority": 3
        },
        {
            "msg_name": "f7_testing_bl_cmd",
            "msg_desc": "Bootloader command for f7 testing",
            "signals": [
                {
                    "sig_name": "cmd",
                    "sig_desc": "Bootloader Command type",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "data",
                    "sig_desc": "Bootloader data",
                    "type": "uint32_t",
                    "length": 32
                }
            ],
            "msg_period": 0,
            "msg_priority": 3
        },
        {
            "msg_name": "daq_bl_cmd",
            "msg_desc": "Bootloader command for DAQ",
            "signals": [
                {
                    "sig_name": "cmd",
                    "sig_desc": "Bootloader Command type",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "data",
                    "sig_desc": "Bootloader data",
                    "type": "uint32_t",
                    "length": 32
                }
            ],
            "msg_period": 0,
            "msg_priority": 3
        },
        {
            "msg_name": "set_fault",
            "msg_desc": "Set a fault",
            "signals": [
                {
                    "sig_name": "id",
                    "sig_desc": "Bootloader Command type",
                    "type": "uint16_t",
                    "length": 16
                },
                {
                    "sig_name": "value",
                    "sig_desc": "Bootloader data",
                    "type": "uint8_t",
                    "length": 1
                }
            ],
            "msg_period": 0,
            "msg_priority": 3
        },
        {
            "msg_name": "return_fault_control",
            "msg_desc": "Return control of fault back to the MCU",
            "signals": [
                {
                    "sig_name": "id",
                    "sig_desc": "Fault ID",
                    "type": "uint16_t",
                    "length": 16
                }
            ],
            "msg_period": 0,
            "msg_priority": 3
        }
    ],
    "rx": []
}
