=== PurdueElectricRacing/firmware/common/can_library/schema/external_node_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "required": ["node_name", "bus_name"],
    "additionalProperties": false,
    "properties": {
        "node_name": { "type": "string" },
        "bus_name": { "type": "string" },
        "tx": {
            "type": "array",
            "items": { "$ref": "file:///message_schema.json#/$defs/tx_message" }
        },
        "rx": {
            "type": "array",
            "items": { "$ref": "file:///message_schema.json#/$defs/rx_message" }
        }
    }
}

=== PurdueElectricRacing/firmware/common/can_library/configs/external_nodes/INVERTER_B.json
{
    "node_name": "INVERTER_B",
    "bus_name": "MCAN",
    "tx": [
        {
            "msg_name": "INVB_CRIT",
            "msg_desc": "Contains the status word and actual values",
            "signals": [
                {
                    "sig_name": "AMK_ActualSpeed",
                    "sig_desc": "Actual speed value",
                    "type": "int16_t",
                    "unit": "rpm"
                },
                {
                    "sig_name": "AMK_ActualTorque",
                    "sig_desc": "Actual torque value",
                    "type": "int16_t",
                    "unit": "%",
                    "scale": 0.1
                },
                {
                    "sig_name": "AMK_DisplayOverloadInverter",
                    "type": "uint16_t",
                    "scale": 0.1,
                    "unit": "%"
                },
                {
                    "sig_name": "AMK_DisplayOverloadMotor",
                    "type": "uint16_t",
                    "scale": 0.1,
                    "unit": "%"
                }
            ],
            "msg_period": 15,
            "msg_id_override": "0x122",
            "msg_priority": 1
        },
        {
            "msg_name": "INVB_INFO",
            "msg_desc": "Contains the status word and actual values",
            "signals": [
                {
                    "sig_name": "AMK_Status_bReserve",
                    "sig_desc": "Status word: RESERVED",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "AMK_Status_bSystemReady",
                    "sig_desc": "Status word: system ready",
                    "type": "bool"
                },
                {
                    "sig_name": "AMK_Status_bError",
                    "sig_desc": "Status word: error",
                    "type": "bool"
                },
                {
                    "sig_name": "AMK_Status_bWarn",
                    "sig_desc": "Status word: warning",
                    "type": "bool"
                },
                {
                    "sig_name": "AMK_Status_bQuitDcOn",
                    "sig_desc": "Status word: HV activation ACK",
                    "type": "bool"
                },
                {
                    "sig_name": "AMK_Status_bDcOn",
                    "sig_desc": "Status word: HV activation level",
                    "type": "bool"
                },
                {
                    "sig_name": "AMK_Status_bQuitInverterOn",
                    "sig_desc": "Status word: Controller enable ACK",
                    "type": "bool"
                },
                {
                    "sig_name": "AMK_Status_bInverterOn",
                    "sig_desc": "Status word: Controller enable level",
                    "type": "bool"
                },
                {
                    "sig_name": "AMK_Status_bDerating",
                    "sig_desc": "Status word: torque limit activation",
                    "type": "bool"
                },
                {
                    "sig_name": "AMK_DCBusVoltage",
                    "sig_desc": "Voltage of the DC bus",
                    "type": "uint16_t",
                    "unit": "V"
                }
            ],
            "msg_period": 500,
            "msg_id_override": "0x232",
            "msg_priority": 2
        },
        {
            "msg_name": "INVB_ERR_1",
            "msg_desc": "All error information",
            "signals": [
                {
                    "sig_name": "AMK_DiagnosticNumber",
                    "sig_desc": "Error number",
                    "type": "uint32_t"
                },
                {
                    "sig_name": "AMK_ErrorInfo1",
                    "sig_desc": "Error info",
                    "type": "uint32_t"
                }
            ],
            "msg_period": 2000,
            "msg_id_override": "0x442",
            "msg_priority": 4
        },
        {
            "msg_name": "INVB_ERR_2",
            "msg_desc": "All error information",
            "signals": [
                {
                    "sig_name": "AMK_ErrorInfo2",
                    "sig_desc": "Error info",
                    "type": "uint32_t"
                },
                {
                    "sig_name": "AMK_ErrorInfo3",
                    "sig_desc": "Error info",
                    "type": "uint32_t"
                }
            ],
            "msg_period": 2000,
            "msg_id_override": "0x452",
            "msg_priority": 4
        },
        {
            "msg_name": "INVB_TEMPS",
            "msg_desc": "Contains temperatures",
            "signals": [
                {
                    "sig_name": "AMK_MotorTemp",
                    "sig_desc": "Motor temperature",
                    "type": "int16_t",
                    "unit": "C",
                    "scale": 0.1
                },
                {
                    "sig_name": "AMK_InverterTemp",
                    "sig_desc": "Inverter cold plate temperature",
                    "type": "int16_t",
                    "unit": "C",
                    "scale": 0.1
                },
                {
                    "sig_name": "AMK_IGBTTemp",
                    "sig_desc": "IGBT temperature",
                    "type": "int16_t",
                    "unit": "C",
                    "scale": 0.1
                }
            ],
            "msg_period": 500,
            "msg_id_override": "0x462",
            "msg_priority": 4
        },
        {
            "msg_name": "INVB_PHASE_I",
            "msg_desc": "All error information",
            "signals": [
                {
                    "sig_name": "AMK_PhaseUCurrent",
                    "sig_desc": "INVB Phase U Current",
                    "type": "int32_t"
                }
            ],
            "msg_period": 250,
            "msg_id_override": "0x572",
            "msg_priority": 5
        }
    ],
    "rx": [
        {
            "msg_name": "INVB_SET"
        }
    ]
}

=== PurdueElectricRacing/firmware/common/can_library/configs/external_nodes/IZZE_IMU.json
{
    "node_name": "IZZE_IMU",
    "bus_name": "VCAN",
    "tx": [
        {
            "msg_name": "Angular_Rate",
            "msg_desc": "Angular Rate",
            "signals": [
                {
                    "sig_name": "X_axis",
                    "sig_desc": "Angular Rate around X-axis",
                    "type": "int16_t",
                    "unit": "deg/s",
                    "scale": 0.1
                },
                {
                    "sig_name": "Y_axis",
                    "sig_desc": "Angular Rate around Y-axis",
                    "type": "int16_t",
                    "unit": "deg/s",
                    "scale": 0.1
                },
                {
                    "sig_name": "Z_axis",
                    "sig_desc": "Angular Rate around Z-axis",
                    "type": "int16_t",
                    "unit": "deg/s",
                    "scale": 0.1
                },
                {
                    "sig_name": "reserved",
                    "sig_desc": "reserved",
                    "type": "uint16_t"
                }
            ],
            "msg_period": 10,
            "msg_id_override": "0x4EC",
            "msg_priority": 5
        },
        {
            "msg_name": "Acceleration",
            "msg_desc": "Acceleration",
            "signals": [
                {
                    "sig_name": "X_axis",
                    "sig_desc": "Acceleration along X-axis",
                    "type": "int16_t",
                    "unit": "g",
                    "scale": 0.01
                },
                {
                    "sig_name": "Y_axis",
                    "sig_desc": "Acceleration along Y-axis",
                    "type": "int16_t",
                    "unit": "g",
                    "scale": 0.01
                },
                {
                    "sig_name": "Z_axis",
                    "sig_desc": "Acceleration along Z-axis",
                    "type": "int16_t",
                    "unit": "g",
                    "scale": 0.01
                },
                {
                    "sig_name": "temperature",
                    "sig_desc": "IMU Temperature",
                    "type": "int16_t",
                    "unit": "C",
                    "scale": 0.1
                }
            ],
            "msg_period": 10,
            "msg_id_override": "0x4ED",
            "msg_priority": 5
        }
    ],
    "rx": [
        {
            "msg_name": "IZZE_IMU_config"
        }
    ]
}

=== PurdueElectricRacing/firmware/common/can_library/configs/external_nodes/INVERTER_A.json
{
    "node_name": "INVERTER_A",
    "bus_name": "VCAN",
    "tx": [
        {
            "msg_name": "INVA_CRIT",
            "msg_desc": "Contains the status word and actual values",
            "signals": [
                {
                    "sig_name": "AMK_ActualSpeed",
                    "sig_desc": "Actual speed value",
                    "type": "int16_t",
                    "unit": "rpm"
                },
                {
                    "sig_name": "AMK_ActualTorque",
                    "sig_desc": "Actual torque value",
                    "type": "int16_t",
                    "unit": "%",
                    "scale": 0.1
                },
                {
                    "sig_name": "AMK_DisplayOverloadInverter",
                    "type": "uint16_t",
                    "scale": 0.1
                },
                {
                    "sig_name": "AMK_DisplayOverloadMotor",
                    "type": "uint16_t",
                    "scale": 0.1
                }
            ],
            "msg_period": 15,
            "msg_id_override": "0x282",
            "msg_priority": 3
        },
        {
            "msg_name": "INVA_TEMPS",
            "msg_desc": "Contains temperatures",
            "signals": [
                {
                    "sig_name": "AMK_MotorTemp",
                    "sig_desc": "Motor temperature",
                    "type": "int16_t",
                    "unit": "C",
                    "scale": 0.1
                },
                {
                    "sig_name": "AMK_InverterTemp",
                    "sig_desc": "Inverter cold plate temperature",
                    "type": "int16_t",
                    "unit": "C",
                    "scale": 0.1
                },
                {
                    "sig_name": "AMK_IGBTTemp",
                    "sig_desc": "IGBT temperature",
                    "type": "int16_t",
                    "unit": "C",
                    "scale": 0.1
                }
            ],
            "msg_period": 500,
            "msg_id_override": "0x284",
            "msg_priority": 3
        },
        {
            "msg_name": "INVA_INFO",
            "msg_desc": "Contains the status word and actual values",
            "signals": [
                {
                    "sig_name": "AMK_Status_bReserve",
                    "sig_desc": "Status word: RESERVED",
                    "type": "uint8_t",
                    "length": 8
                },
                {
                    "sig_name": "AMK_Status_bSystemReady",
                    "sig_desc": "Status word: system ready",
                    "type": "uint8_t",
                    "length": 1
                },
                {
                    "sig_name": "AMK_Status_bError",
                    "sig_desc": "Status word: error",
                    "type": "uint8_t",
                    "length": 1
                },
                {
                    "sig_name": "AMK_Status_bWarn",
                    "sig_desc": "Status word: warning",
                    "type": "uint8_t",
                    "length": 1
                },
                {
                    "sig_name": "AMK_Status_bQuitDcOn",
                    "sig_desc": "Status word: HV activation ACK",
                    "type": "uint8_t",
                    "length": 1
                },
                {
                    "sig_name": "AMK_Status_bDcOn",
                    "sig_desc": "Status word: HV activation level",
                    "type": "uint8_t",
                    "length": 1
                },
                {
                    "sig_name": "AMK_Status_bQuitInverterOn",
                    "sig_desc": "Status word: Controller enable ACK",
                    "type": "uint8_t",
                    "length": 1
                },
                {
                    "sig_name": "AMK_Status_bInverterOn",
                    "sig_desc": "Status word: Controller enable level",
                    "type": "uint8_t",
                    "length": 1
                },
                {
                    "sig_name": "AMK_Status_bDerating",
                    "sig_desc": "Status word: torque limit activation",
                    "type": "uint8_t",
                    "length": 1
                },
                {
                    "sig_name": "AMK_DCBusVoltage",
                    "sig_desc": "Voltage of the DC bus",
                    "type": "uint16_t",
                    "unit": "V"
                }
            ],
            "msg_period": 500,
            "msg_id_override": "0x286",
            "msg_priority": 3
        },
        {
            "msg_name": "INVA_ERR_1",
            "msg_desc": "All error information",
            "signals": [
                {
                    "sig_name": "AMK_DiagnosticNumber",
                    "sig_desc": "Error number",
                    "type": "uint32_t"
                },
                {
                    "sig_name": "AMK_ErrorInfo1",
                    "sig_desc": "Error info",
                    "type": "uint32_t"
                }
            ],
            "msg_period": 2000,
            "msg_id_override": "0x288",
            "msg_priority": 3
        },
        {
            "msg_name": "INVA_ERR_2",
            "msg_desc": "All error information",
            "signals": [
                {
                    "sig_name": "AMK_ErrorInfo2",
                    "sig_desc": "Error info",
                    "type": "uint32_t"
                },
                {
                    "sig_name": "AMK_ErrorInfo3",
                    "sig_desc": "Error info",
                    "type": "uint32_t"
                }
            ],
            "msg_period": 2000,
            "msg_id_override": "0x290",
            "msg_priority": 3
        },
        {
            "msg_name": "INVA_PHASE_I",
            "msg_desc": "All error information",
            "signals": [
                {
                    "sig_name": "AMK_PhaseUCurrent",
                    "sig_desc": "INVA Phase U Current",
                    "type": "int32_t"
                }
            ],
            "msg_period": 250,
            "msg_id_override": "0x292",
            "msg_priority": 3
        }
    ],
    "rx": [
        {
            "msg_name": "INVA_SET"
        }
    ]
}

=== PurdueElectricRacing/firmware/common/can_library/configs/external_nodes/BOOTLOADER.json
{
    "node_name": "BOOTLOADER",
    "bus_name": "VCAN",
    "tx": [
        {
            "msg_name": "bl_main_module_cmd",
            "msg_desc": "Bootloader command for main module",
            "signals": [
                {
                    "sig_name": "cmd",
                    "type": "uint8_t"
                },
                {
                    "sig_name": "data",
                    "type": "uint32_t"
                }
            ],
            "msg_id_override": "0x180",
            "msg_priority": 0
        },
        {
            "msg_name": "bl_main_module_data",
            "msg_desc": "Bootloader firmware data for main module",
            "signals": [
                {
                    "sig_name": "index",
                    "type": "uint16_t"
                },
                {
                    "sig_name": "data",
                    "type": "uint32_t"
                }
            ],
            "msg_id_override": "0x181",
            "msg_priority": 0
        },
        {
            "msg_name": "bl_dashboard_cmd",
            "msg_desc": "Bootloader command for dashboard",
            "signals": [
                {
                    "sig_name": "cmd",
                    "type": "uint8_t"
                },
                {
                    "sig_name": "data",
                    "type": "uint32_t"
                }
            ],
            "msg_id_override": "0x183",
            "msg_priority": 0
        },
        {
            "msg_name": "bl_dashboard_data",
            "msg_desc": "Bootloader firmware data for dashboard",
            "signals": [
                {
                    "sig_name": "index",
                    "type": "uint16_t"
                },
                {
                    "sig_name": "data",
                    "type": "uint32_t"
                }
            ],
            "msg_id_override": "0x184",
            "msg_priority": 0
        },
        {
            "msg_name": "bl_torque_vector_cmd",
            "msg_desc": "Bootloader command for torque vector",
            "signals": [
                {
                    "sig_name": "cmd",
                    "type": "uint8_t"
                },
                {
                    "sig_name": "data",
                    "type": "uint32_t"
                }
            ],
            "msg_id_override": "0x186",
            "msg_priority": 0
        },
        {
            "msg_name": "bl_torque_vector_data",
            "msg_desc": "Bootloader firmware data for torque vector",
            "signals": [
                {
                    "sig_name": "index",
                    "type": "uint16_t"
                },
                {
                    "sig_name": "data",
                    "type": "uint32_t"
                }
            ],
            "msg_id_override": "0x187",
            "msg_priority": 0
        },
        {
            "msg_name": "bl_a_box_cmd",
            "msg_desc": "Bootloader command for a box",
            "signals": [
                {
                    "sig_name": "cmd",
                    "type": "uint8_t"
                },
                {
                    "sig_name": "data",
                    "type": "uint32_t"
                }
            ],
            "msg_id_override": "0x189",
            "msg_priority": 0
        },
        {
            "msg_name": "bl_a_box_data",
            "msg_desc": "Bootloader firmware data for a box",
            "signals": [
                {
                    "sig_name": "index",
                    "type": "uint16_t"
                },
                {
                    "sig_name": "data",
                    "type": "uint32_t"
                }
            ],
            "msg_id_override": "0x18A",
            "msg_priority": 0
        },
        {
            "msg_name": "bl_pdu_cmd",
            "msg_desc": "Bootloader command for pdu",
            "signals": [
                {
                    "sig_name": "cmd",
                    "type": "uint8_t"
                },
                {
                    "sig_name": "data",
                    "type": "uint32_t"
                }
            ],
            "msg_id_override": "0x18C",
            "msg_priority": 0
        },
        {
            "msg_name": "bl_pdu_data",
            "msg_desc": "Bootloader firmware data for pdu",
            "signals": [
                {
                    "sig_name": "index",
                    "type": "uint16_t"
                },
                {
                    "sig_name": "data",
                    "type": "uint32_t"
                }
            ],
            "msg_id_override": "0x18D",
            "msg_priority": 0
        },
        {
            "msg_name": "bl_driveline_cmd",
            "msg_desc": "Bootloader command for driveline",
            "signals": [
                {
                    "sig_name": "cmd",
                    "type": "uint8_t"
                },
                {
                    "sig_name": "data",
                    "type": "uint32_t"
                }
            ],
            "msg_id_override": "0x18F",
            "msg_priority": 0
        },
        {
            "msg_name": "bl_driveline_data",
            "msg_desc": "Bootloader firmware data for driveline",
            "signals": [
                {
                    "sig_name": "index",
                    "type": "uint16_t"
                },
                {
                    "sig_name": "data",
                    "type": "uint32_t"
                }
            ],
            "msg_id_override": "0x190",
            "msg_priority": 0
        },
        {
            "msg_name": "bl_g4_testing_cmd",
            "msg_desc": "Bootloader command for g4 testing",
            "signals": [
                {
                    "sig_name": "cmd",
                    "type": "uint8_t"
                },
                {
                    "sig_name": "data",
                    "type": "uint32_t"
                }
            ],
            "msg_id_override": "0x192",
            "msg_priority": 0
        },
        {
            "msg_name": "bl_g4_testing_data",
            "msg_desc": "Bootloader firmware data for g4 testing",
            "signals": [
                {
                    "sig_name": "index",
                    "type": "uint16_t"
                },
                {
                    "sig_name": "data",
                    "type": "uint32_t"
                }
            ],
            "msg_id_override": "0x193",
            "msg_priority": 0
        }
    ],
    "rx": [
        {
            "msg_name": "bl_main_module_resp"
        },
        {
            "msg_name": "bl_dashboard_resp"
        },
        {
            "msg_name": "bl_torque_vector_resp"
        },
        {
            "msg_name": "bl_a_box_resp"
        },
        {
            "msg_name": "bl_pdu_resp"
        },
        {
            "msg_name": "bl_driveline_resp"
        },
        {
            "msg_name": "bl_g4_testing_resp"
        }
    ]
}

=== PurdueElectricRacing/firmware/common/can_library/configs/external_nodes/DAQ_APP.json
{
    "node_name": "DAQ_APP",
    "bus_name": "CCAN",
    "tx": [
        {
            "msg_name": "charge_request",
            "msg_desc": "Message from DAQ App to A_BOX to request charging",
            "signals": [
                {
                    "sig_name": "charge_enable",
                    "sig_desc": "Request to start charging",
                    "type": "bool"
                },
                {
                    "sig_name": "charge_voltage",
                    "sig_desc": "Requested charge voltage in decivolts",
                    "type": "uint16_t",
                    "unit": "V",
                    "scale": 0.1
                },
                {
                    "sig_name": "charge_current",
                    "sig_desc": "Requested charge current in deciamps",
                    "type": "uint16_t",
                    "unit": "A",
                    "scale": 0.1
                }
            ],
            "msg_period": 500,
            "msg_priority": 3
        }
    ],
    "rx": [
        {
            "msg_name": "elcon_status"
        },
        {
            "msg_name": "charging_telemetry"
        }
    ]
}

=== PurdueElectricRacing/firmware/common/can_library/configs/external_nodes/ELCON_CHARGER.json
{
    "node_name": "ELCON_CHARGER",
    "bus_name": "CCAN",
    "tx": [
        {
            "msg_name": "elcon_charger_status",
            "msg_desc": "Realtime charger status",
            "signals": [
                {
                    "sig_name": "charge_voltage",
                    "unit": "V",
                    "scale": 0.1,
                    "type": "uint16_t"
                },
                {
                    "sig_name": "charge_current",
                    "unit": "A",
                    "scale": 0.1,
                    "type": "uint16_t"
                },
                {
                    "sig_name": "hw_fail",
                    "sig_desc": "Hardware failure",
                    "type": "bool"
                },
                {
                    "sig_name": "temp_fail",
                    "sig_desc": "Temperature failure",
                    "type": "bool"
                },
                {
                    "sig_name": "input_v_fail",
                    "sig_desc": "Input voltage failure",
                    "type": "bool"
                },
                {
                    "sig_name": "startup_fail",
                    "sig_desc": "Startup voltage detection failure",
                    "type": "bool"
                },
                {
                    "sig_name": "communication_fail",
                    "sig_desc": " 5s timeout from communication failure",
                    "type": "bool"
                }
            ],
            "msg_id_override": "0x18FF50E5",
            "msg_period": 2000,
            "msg_priority": 3
        }
    ],
    "rx": []
}

=== PurdueElectricRacing/firmware/common/can_library/configs/external_nodes/BOSCH_LWS.json
{
    "node_name": "BOSCH_LWS",
    "bus_name": "SCAN",
    "tx": [
        {
            "msg_name": "LWS_Standard",
            "msg_desc": "Standard steering angle and speed",
            "signals": [
                {
                    "sig_name": "LWS_ANGLE",
                    "sig_desc": "Steering Angle",
                    "type": "int16_t",
                    "unit": "deg",
                    "scale": 0.1
                },
                {
                    "sig_name": "LWS_SPEED",
                    "sig_desc": "Angular speed of steering input",
                    "type": "uint8_t",
                    "unit": "deg/s",
                    "scale": 4,
                    "length": 8
                },
                {
                    "sig_name": "OK",
                    "sig_desc": "Sensor failure status, 0 = failure, 1 = OK",
                    "type": "bool"
                },
                {
                    "sig_name": "CAL",
                    "sig_desc": "Sensor calibration status, 0 = uncalibrated, 1 = calibrated",
                    "type": "bool"
                },
                {
                    "sig_name": "TRIM",
                    "sig_desc": "Sensor trim status, 0 = invalid, 1 = valid",
                    "type": "bool"
                },
                {
                    "sig_name": "reserved1",
                    "type": "uint8_t",
                    "length": 5
                },
                {
                    "sig_name": "reserved2",
                    "type": "uint8_t",
                    "length": 8
                }
            ],
            "msg_period": 10,
            "msg_id_override": "0x2B0",
            "msg_priority": 3
        }
    ],
    "rx": []
}
