=== PurdueElectricRacing/firmware/can_library/schema/node.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "required": ["node_name", "busses", "fault_library_enabled"],
    "additionalProperties": false,
    "properties": {
        "node_name": { "type": "string" },
        "busses": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/$defs/bus_messages"
            },
            "minProperties": 1
        },
        "fault_library_enabled": {
            "type": "boolean",
            "default": true
        },
        "generate_fault_messages": {
            "type": "boolean"
        },
        "faults": {
            "type": "array",
            "items": { "$ref": "https://github.com/PER/canpiler/fault.schema.json" },
            "uniqueItems": true
        }
    },
    "if": {
        "required": ["faults"]
    },
    "then": {
        "properties": {
            "fault_library_enabled": { "const": true }
        }
    },
    "$defs": {
        "bus_messages": {
            "type": "object",
            "required": ["peripheral"],
            "unevaluatedProperties": false,
            "properties": {
                "peripheral": { "enum": ["CAN1", "CAN2", "FDCAN1", "FDCAN2", "FDCAN3"] },
                "accept_all_messages": { "type": "boolean" },
                "tx": {
                    "type": "array",
                    "items": { "$ref": "https://github.com/PER/canpiler/message.schema.json#/$defs/tx_message" }
                },
                "rx": {
                    "type": "array",
                    "items": { "$ref": "https://github.com/PER/canpiler/message.schema.json#/$defs/rx_message" }
                }
            }
        }
    }
}

=== PurdueElectricRacing/firmware/can_library/configs/nodes/DASHBOARD.json
{
    "node_name": "DASHBOARD",
    "busses": {
        "VCAN": {
            "peripheral": "FDCAN2",
            "tx": [
                {
                    "msg_name": "dash_init",
                    "msg_desc": "DASH hardware initialized",
                    "signals": [
                        {
                            "sig_name": "csr",
                            "sig_desc": "RCC CSR register",
                            "type": "uint32_t"
                        }
                    ],
                    "msg_priority": 0
                },
                {
                    "msg_name": "pedals",
                    "msg_desc": "Pedal values",
                    "signals": [
                        {
                            "sig_name": "throttle",
                            "sig_desc": "throttle request from driver",
                            "type": "uint8_t",
                            "min": 0,
                            "max": 100,
                            "unit": "%"
                        },
                        {
                            "sig_name": "regen",
                            "sig_desc": "regen request from driver (first throw)",
                            "type": "uint8_t",
                            "min": 0,
                            "max": 100,
                            "unit": "%"
                        },
                        {
                            "sig_name": "brake",
                            "sig_desc": "mechanical braking from driver (second throw)",
                            "type": "uint8_t",
                            "min": 0,
                            "max": 100,
                            "unit": "%"
                        }
                    ],
                    "msg_period": 15,
                    "msg_priority": 2
                },
                {
                    "msg_name": "start_button",
                    "msg_desc": "Car start button",
                    "signals": [
                        {
                            "sig_name": "is_pressed",
                            "type": "bool"
                        }
                    ],
                    "msg_period": 200,
                    "msg_priority": 1
                },
                {
                    "msg_name": "vcu_driver_request",
                    "msg_desc": "driver requested VCU settings",
                    "signals": [
                        {
                            "sig_name": "vcu_mode",
                            "type": "vcu_mode_t"
                        },
                        {
                            "sig_name": "lateral_gain",
                            "type": "uint8_t",
                            "unit": "%",
                            "max": 100,
                            "min": 0
                        },
                        {
                            "sig_name": "longitudinal_gain",
                            "type": "uint8_t",
                            "unit": "%",
                            "max": 100,
                            "min": 0
                        },
                        {
                            "sig_name": "electronic_brake_bias",
                            "type": "uint8_t",
                            "unit": "%",
                            "max": 100,
                            "min": 0
                        },
                        {
                            "sig_name": "is_regen_enabled",
                            "type": "bool"
                        },
                        {
                            "sig_name": "is_tv_enabled",
                            "type": "bool"
                        }
                    ],
                    "msg_priority": 3
                },
                {
                    "msg_name": "steering_angle",
                    "msg_desc": "steering data",
                    "signals": [
                        {
                            "sig_name": "angle",
                            "type": "int16_t",
                            "unit": "deg",
                            "scale": 0.1
                        },
                        {
                            "sig_name": "angular_rate",
                            "type": "uint16_t",
                            "unit": "deg/s",
                            "scale": 4
                        },
                        {
                            "sig_name": "data_valid",
                            "type": "bool"
                        }
                    ],
                    "msg_period": 50,
                    "msg_priority": 4
                },
                {
                    "msg_name": "mark_data",
                    "msg_desc": "Mark data for telemetry correlation",
                    "signals": [
                        {
                            "sig_name": "os_tick",
                            "type": "uint32_t",
                            "sig_desc": "milliseconds since startup"
                        },
                        {
                            "sig_name": "mark_index",
                            "type": "uint16_t",
                            "sig_desc": "incremented each time the mark button is pressed"
                        }
                    ],
                    "msg_priority": 4,
                    "msg_period": 0
                },
                {
                    "msg_name": "dash_version",
                    "msg_desc": "Dashboard version",
                    "signals": [
                        {
                            "sig_name": "git_hash",
                            "type": "uint32_t",
                            "sig_desc": "int representation of git short hash"
                        }
                    ],
                    "msg_priority": 5,
                    "msg_period": 5000
                }
            ],
            "rx": [
                {
                    "msg_name": "main_hb"
                },
                {
                    "msg_name": "pack_stats"
                },
                {
                    "msg_name": "wheel_speeds"
                },
                {
                    "msg_name": "motor_temps"
                },
                {
                    "msg_name": "igbt_temps"
                },
                {
                    "msg_name": "inva_diagnostics"
                },
                {
                    "msg_name": "invb_diagnostics"
                },
                {
                    "msg_name": "invc_diagnostics"
                },
                {
                    "msg_name": "invd_diagnostics"
                },
                {
                    "msg_name": "vcu_settings",
                    "callback": true
                },
                {
                    "msg_name": "vcu_torque_request"
                }
            ]
        },
        "SCAN": {
            "peripheral": "FDCAN3",
            "tx": [
                {
                    "msg_name": "LWS_Config",
                    "msg_desc": "Steering sensor configuration",
                    "signals": [
                        {
                            "sig_name": "CCW",
                            "sig_desc": "Command Code Word",
                            "type": "uint8_t",
                            "length": 3
                        },
                        {
                            "sig_name": "reserved1",
                            "type": "uint8_t",
                            "length": 5
                        },
                        {
                            "sig_name": "reserved2",
                            "type": "uint8_t",
                            "length": 8
                        }
                    ],
                    "msg_period": 0,
                    "msg_id_override": "0x7C0",
                    "msg_priority": 3
                }
            ],
            "rx": [
                {
                    "msg_name": "LWS_Standard",
                    "callback": true
                }
            ]
        }
    },
    "fault_library_enabled": true,
    "generate_fault_messages": true,
    "faults": [
        {
            "fault_name": "APPS_wiring_t1",
            "max": 4095,
            "min": 0,
            "priority": "error",
            "time_to_latch": 200,
            "time_to_unlatch": 1000,
            "lcd_message": "APPS Wiring Fail T1"
        },
        {
            "fault_name": "APPS_wiring_t2",
            "max": 3650,
            "min": 0,
            "priority": "error",
            "time_to_latch": 200,
            "time_to_unlatch": 1000,
            "lcd_message": "APPS Wiring Fail T2"
        },
        {
            "fault_name": "APPS_IMPLAUSIBLE",
            "max": 10,
            "min": 0,
            "priority": "error",
            "time_to_latch": 500,
            "time_to_unlatch": 50,
            "lcd_message": "APPS Implaus Detected"
        },
        {
            "fault_name": "APPS_BRAKE",
            "max": 1,
            "min": 0,
            "priority": "warning",
            "time_to_latch": 200,
            "time_to_unlatch": 100,
            "lcd_message": "Release Both Pedals"
        },
        {
            "fault_name": "BSE",
            "max": 4000,
            "min": 300,
            "priority": "error",
            "time_to_latch": 200,
            "time_to_unlatch": 50,
            "lcd_message": "Brake pressure disconnected"
        }
    ]
}
